### ISSUE TITLE
解包之后并没有w或者温蒂立绘

### ISSUE THREAD

**Issue by Zzzzzzouhang** [JiXiaoYao/ArknightsResourceTools#2]
我今天超级想看w立绘，然后解包之后没找到呜呜呜

**Comment by JiXiaoYao** [comment]
你确定包的版本是官网下载的最新等包么

**Comment by Zzzzzzouhang** [comment]
确定啊

**Comment by Zzzzzzouhang** [comment]
我刚才又去使用AssetStudio解包找，也没有找到，感觉可能是官网包的问题

**Comment by JiXiaoYao** [comment]
你试试看打包手机上的数据去解包看看

**Comment by JiXiaoYao** [comment]
我这边手机文件打包确认了一下，只有w普通立绘，精2找不到

**Comment by JiXiaoYao** [comment]
**你要把手机中的明日方舟安装包下的AB文件夹打包发送到电脑解包，我现在确认了一下，W和weedy的包应该是yj动态下载的，不在安装包之内，w要搜索cqbw，温蒂要搜索weedy**
W(cqbw):
![image](https://user-images.githubusercontent.com/26181058/83469107-c652b400-a44c-11ea-9a7a-f7707734582a.png)
温蒂(weedy):
![image](https://user-images.githubusercontent.com/26181058/83469142-dd91a180-a44c-11ea-816f-7945100eaf76.png)

**Comment by Zzzzzzouhang** [comment]
太感谢了，我找了
